(() => {
if (window.innerWidth < 1000) return;
const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
const css=document.createElement('style');css.textContent=`.x-palette{position:fixed;inset:0;z-index:22000;display:grid;place-items:start center;padding:12vh 18px 18px;background:#020104b8;backdrop-filter:blur(18px);opacity:0;pointer-events:none;transition:.18s}.x-palette.open{opacity:1;pointer-events:auto}.x-palette-box{width:min(650px,100%);border:1px solid #e7c6ff30;border-radius:25px;background:#09050ff7;box-shadow:0 50px 180px #000d;overflow:hidden;transform:translateY(-10px) scale(.985);transition:.18s}.x-palette.open .x-palette-box{transform:none}.x-palette-input{width:100%;padding:20px 22px;border:0!important;border-bottom:1px solid #ffffff0d!important;background:transparent!important;color:#fff!important;outline:0!important;font:750 16px Inter,system-ui!important}.x-palette-list{max-height:390px;overflow:auto;padding:8px}.x-palette-item{display:flex;width:100%;align-items:center;justify-content:space-between;gap:15px;padding:13px 14px;border:0;border-radius:14px;background:transparent;color:#b9acbf;text-align:left;cursor:pointer}.x-palette-item:hover,.x-palette-item.active{background:#a75cf319;color:#fff}.x-palette-item small{color:#756a7e;font-size:9px;letter-spacing:.1em}.x-palette-key{position:fixed;right:18px;bottom:72px;z-index:10990;padding:9px 12px;border:1px solid #ffffff13;border-radius:999px;background:#08040dbf;color:#746a7c;font:800 9px Inter,system-ui;backdrop-filter:blur(18px)}.x-events{margin-top:30px;border:1px solid #e7c6ff1b;border-radius:22px;background:#ffffff04;padding:15px}.x-event{display:flex;align-items:center;gap:11px;padding:10px 8px;color:#8f8299;font:650 11px Inter,system-ui;border-bottom:1px solid #ffffff08}.x-event:last-child{border-bottom:0}.x-event i{width:7px;height:7px;flex:0 0 7px;border-radius:50%;background:#68e6aa;box-shadow:0 0 10px #68e6aa}.x-event time{margin-left:auto;color:#61576a;font:700 9px ui-monospace,monospace}.x-live-bump{animation:xLiveBump .42s ease}@keyframes xLiveBump{50%{transform:translateY(-3px);filter:brightness(1.2)}}`;document.head.appendChild(css);
const live=document.getElementById('live');if(live){const feed=document.createElement('div');feed.className='x-events';feed.innerHTML='<div class="x-event"><i></i><span>Runtime endpoint connected</span><time>LIVE</time></div><div class="x-event"><i></i><span>Command database ready</span><time>100 CMD</time></div><div class="x-event"><i></i><span>OAuth + SQLite systems available</span><time>READY</time></div>';live.appendChild(feed)}
const demo=document.querySelector('.x-demo');if(demo){const tabs=[...demo.querySelectorAll('[data-demo]')];let i=0,paused=false;demo.addEventListener('mouseenter',()=>paused=true);demo.addEventListener('mouseleave',()=>paused=false);setInterval(()=>{if(paused||document.hidden||!tabs.length)return;i=(i+1)%tabs.length;tabs[i].click()},4200)}
const items=[['Live status','#live','SECTION'],['Systems','#systems','SECTION'],['Commands','#commands','SECTION'],['Terminal','#terminal','SECTION'],['Architecture','#architecture','SECTION'],['Contact','#contact','SECTION']];
const cmdNames=['ping','help','userinfo','avatar','serverinfo','uptime','clear','kick','ban','timeout','setup','birthday','confess','server-health','member-stats','about'];cmdNames.forEach(c=>items.push([`/${c}`,`cmd:${c}`,'COMMAND']));
const pal=document.createElement('div');pal.className='x-palette';pal.innerHTML='<div class="x-palette-box"><input class="x-palette-input" placeholder="Jump anywhere or find a command…"><div class="x-palette-list"></div></div>';document.body.appendChild(pal);const hint=document.createElement('div');hint.className='x-palette-key';hint.textContent='⌘/Ctrl K  COMMAND PALETTE';document.body.appendChild(hint);const inp=pal.querySelector('input'),list=pal.querySelector('.x-palette-list');let shown=[];
function render(q=''){const s=q.toLowerCase();shown=items.filter(x=>x[0].toLowerCase().includes(s)).slice(0,12);list.innerHTML=shown.map((x,n)=>`<button class="x-palette-item ${n===0?'active':''}" data-i="${n}"><span>${x[0]}</span><small>${x[2]}</small></button>`).join('')||'<div class="x-event">No result.</div>'}render();
function close(){pal.classList.remove('open')}function open(){pal.classList.add('open');render('');setTimeout(()=>inp.focus(),20)}function choose(n){const x=shown[n];if(!x)return;close();if(x[1].startsWith('#')){const el=document.querySelector(x[1]);if(el)el.scrollIntoView({behavior:reduce?'auto':'smooth',block:'start'})}else{const name=x[1].slice(4),search=document.getElementById('search');if(search){search.value=name;search.dispatchEvent(new Event('input',{bubbles:true}));document.getElementById('commands')?.scrollIntoView({behavior:reduce?'auto':'smooth',block:'start'})}}}
addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();pal.classList.contains('open')?close():open()}else if(e.key==='Escape'&&pal.classList.contains('open'))close();else if(e.key==='Enter'&&pal.classList.contains('open'))choose(0)});inp.addEventListener('input',()=>render(inp.value));list.addEventListener('click',e=>{const b=e.target.closest('[data-i]');if(b)choose(+b.dataset.i)});pal.addEventListener('click',e=>{if(e.target===pal)close()});
let old='';setInterval(()=>{const badge=document.getElementById('liveStatusBadge'),now=badge?.textContent?.trim()||'';if(now&&now!==old){old=now;badge.classList.remove('x-live-bump');requestAnimationFrame(()=>badge.classList.add('x-live-bump'))}},1200);
})();