(() => {
  const API='https://4jeo6afdee.apps.bot-hosting.cloud/api/health',FALLBACK_VERSION='11.5',FALLBACK_CORE='MEMBER INTELLIGENCE';
  const $=id=>document.getElementById(id),set=(id,v)=>{const e=$(id);if(e)e.textContent=v;},finite=Number.isFinite;let uptimeBase=null,uptimeFetchedAt=null,lastData=null;
  const core=v=>String(v||FALLBACK_CORE).trim().toUpperCase(),intel=d=>d?.nexus_intelligence||{},auto=d=>d?.nexus_automation||{};
  function uptime(t){t=Math.max(0,Math.floor(t||0));const d=Math.floor(t/86400);t%=86400;const h=Math.floor(t/3600);t%=3600;const m=Math.floor(t/60),s=t%60;return d?`${d}d ${h}h ${m}m`:h?`${h}h ${m}m ${s}s`:m?`${m}m ${s}s`:`${s}s`;}
  function staticCopy(){const text=(s,v)=>{const e=document.querySelector(s);if(e)e.textContent=v;};text('.hero .kicker','DISCORD MEMBER INTELLIGENCE');text('.console-brand','XENOXY MEMBER INTELLIGENCE');text('.console-grid article:first-child span','V11.5 Core');text('main > .metric-strip article:first-child span','Member Intelligence');text('#systems .eyebrow','// V11.5 MEMBER INTELLIGENCE');text('#architecture .eyebrow','// V11.5 INTELLIGENCE ARCHITECTURE');text('footer span:first-child','XENOXY // V11.5 // MEMBER INTELLIGENCE');set('liveVersion','V11.5');const a=document.querySelector('#architecture h2');if(a)a.innerHTML='Discord → Analytics → Members → Intelligence → <span>Xenoxy.</span>';const l=document.querySelector('.hero .lead');if(l)l.textContent='100 verified slash commands, Security Guard, Smart Automod, Rule Builder, message + voice analytics, per-member intelligence, activity scores, heatmaps and leaderboards.';const s=document.querySelector('#systems .sectionhead .muted');if(s)s.textContent='V11.5 transforms Xenoxy analytics into member-level intelligence profiles while preserving the stable Dashboard 2.0, Rule Builder and 100-command core.';}
  function identity(v=FALLBACK_VERSION,c=FALLBACK_CORE){document.title=`Xenoxy V${v} // ${core(c)}`;const m=document.querySelector('meta[name="description"]');if(m)m.content=`Xenoxy V${v} ${core(c)} — 100 Discord commands, member profiles, message + voice analytics, heatmaps, leaderboards and safe automation.`;}
  function state(s,l){const b=$('liveStatusBadge');if(b){b.dataset.state=s;b.innerHTML=`<span class="pulse"></span>${l}`;}}
  function demo(d){const x=document.querySelector('.x-demo');if(!x)return;const active=x.querySelector('[data-demo].active')?.dataset.demo,screen=x.querySelector('.x-demo-screen');if(!screen)return;const title=screen.querySelector('b'),body=screen.querySelector('span'),i=intel(d),t=i.trends_24h||{},r=i.risk||{},a=auto(d);if(active==='members'){if(title&&finite(d.members))title.textContent=`${d.members} members visible`;if(body)body.textContent=`${d.guilds??'—'} guilds • member profiles • message + voice analytics • heatmaps • leaderboards.`;}else if(active==='moderation'){if(title)title.textContent=d.bot_ready?'Member Intelligence online':'Control stack starting';if(body)body.textContent=`Security Guard READY • Smart Automod critical ${r.critical_risk??'—'} • Automation ${String(a.engine||'—').toUpperCase()}.`;}else if(active==='settings'){if(title)title.textContent=`V${d.version||FALLBACK_VERSION} ${core(d.core)}`;if(body)body.textContent=`Nexus ${d.health_score??'—'}/100 • Member Intelligence • Rule Builder • OAuth Dashboard.`;}}
  function hero(d){const v=d.version||FALLBACK_VERSION,c=core(d.core),online=d.bot_ready===true,a=auto(d);identity(v,c);const hs=document.querySelector('.hero .status');if(hs)hs.innerHTML=`<span class="pulse"></span> V${v} ${c} <b>// ${online?'ONLINE':'STARTING'}</b>`;const ho=document.querySelector('.trust-row span:first-child');if(ho)ho.innerHTML=`<i></i> ${online?'MEMBER INTELLIGENCE ONLINE':'PLATFORM STARTING'}${finite(d.health_score)?` • NEXUS ${d.health_score}/100`:''} • AUTO ${a.enabled_guilds??0}`;const cards=document.querySelectorAll('.console-grid article');if(cards[0]?.querySelector('b'))cards[0].querySelector('b').textContent=`V${v}`;if(cards[1]?.querySelector('b')&&finite(d.commands))cards[1].querySelector('b').textContent=d.commands;if(cards[2]?.querySelector('b')&&finite(d.latency_ms))cards[2].querySelector('b').textContent=`${d.latency_ms} ms`;if(cards[3]?.querySelector('b'))cards[3].querySelector('b').textContent=uptimeBase!==null?uptime(uptimeBase):(d.uptime||'—');set('liveVersion',`V${v}`);demo(d);}
  async function refresh(){state('loading','SYNCING V11.5');try{const r=await fetch(API,{cache:'no-store'});if(!r.ok)throw Error(`HTTP ${r.status}`);const d=await r.json();if(!d||d.ok!==true)throw Error('Invalid status payload');lastData=d;const online=d.bot_ready===true,a=auto(d);state(online?'online':'starting',online?`${core(d.core)} ONLINE${finite(d.health_score)?` • ${d.health_score}/100 ${String(d.health_state||'').toUpperCase()}`:''} • AUTO ${a.enabled_guilds??0}`:`${core(d.core)} STARTING`);set('liveVersion',`V${d.version||FALLBACK_VERSION}`);set('liveLatency',finite(d.latency_ms)?`${d.latency_ms} ms`:'—');set('liveGuilds',finite(d.guilds)?String(d.guilds):'—');set('liveMembers',finite(d.members)?String(d.members):'—');set('liveCommands',finite(d.commands)?String(d.commands):'—');set('liveUpdated',d.updated_at?new Date(d.updated_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'}):'just now');uptimeBase=finite(d.uptime_seconds)?d.uptime_seconds:null;uptimeFetchedAt=performance.now();set('liveUptime',uptimeBase!==null?uptime(uptimeBase):(d.uptime||'—'));hero(d);document.documentElement.dataset.xenoxyState=online?'online':'starting';document.documentElement.dataset.memberIntelligence=online?'online':'starting';}catch(e){lastData=null;identity();state('offline','V11.5 OFFLINE • RETRYING');['liveLatency','liveUptime','liveGuilds','liveMembers','liveCommands'].forEach(id=>set(id,'—'));set('liveVersion',`V${FALLBACK_VERSION}`);set('liveUpdated','retrying automatically');uptimeBase=uptimeFetchedAt=null;document.documentElement.dataset.xenoxyState='offline';console.warn('Xenoxy live status unavailable:',e);}}
  window.addEventListener('xenoxy-demo-tab',()=>{if(lastData)demo(lastData);});setInterval(()=>{if(uptimeBase===null||uptimeFetchedAt===null)return;const now=uptimeBase+(performance.now()-uptimeFetchedAt)/1000;set('liveUptime',uptime(now));const c=document.querySelectorAll('.console-grid article');if(c[3]?.querySelector('b'))c[3].querySelector('b').textContent=uptime(now);},1000);staticCopy();identity();refresh();setInterval(refresh,30000);
})();