const commands=['ping','help','userinfo','avatar','joined','serverinfo','servericon','roleinfo','channelinfo','botinfo','uptime','roles','permissions','8ball','coinflip','roll','dice','choose','randomnumber','rate','ship','rps','joke','fact','truth','dare','wouldyourather','compliment','roast','vibecheck','iq','howgay','slots','say','poll','announce','timestamp','calc','remindme','password','color','countdown','embed','length','choose-number','clear','kick','ban','unban','timeout','untimeout','slowmode','nickname','lock','unlock','purge-user','role-add','role-remove','move','channel-create','channel-delete','role-create','role-delete','server-stats','bot-stats','invite','rules','setup','welcome-channel','welcome-toggle','goodbye-channel','goodbye-toggle','log-channel','autorole','autorole-off','suggestion-setup','suggestion','report','server-backup','reaction-role','button-role','setup-reset','birthday','confess','server-health','role-menu','welcome-preview','activity','sticky','embed-builder','verification-setup','suggestion-manage','birthday-list','birthday-remove','sticky-off','confess-setup','member-stats','verification-off','server-age','about'];
const moderation=new Set(['clear','kick','ban','unban','timeout','untimeout','slowmode','nickname','lock','unlock','purge-user','role-add','role-remove','move','report']);
const community=new Set(['suggestion-setup','suggestion','reaction-role','button-role','birthday','confess','role-menu','activity','sticky','suggestion-manage','birthday-list','birthday-remove','sticky-off','confess-setup']);
const server=new Set(['channel-create','channel-delete','role-create','role-delete','server-stats','invite','rules','setup','welcome-channel','welcome-toggle','goodbye-channel','goodbye-toggle','log-channel','autorole','autorole-off','server-backup','setup-reset','welcome-preview','verification-setup','verification-off','server-health','server-age']);
const fun=new Set(['8ball','coinflip','roll','dice','choose','randomnumber','rate','ship','rps','joke','fact','truth','dare','wouldyourather','compliment','roast','vibecheck','iq','howgay','slots']);
const category=c=>moderation.has(c)?'moderation':community.has(c)?'community':server.has(c)?'server':fun.has(c)?'fun':'utility';
const grid=document.getElementById('commandGrid'),search=document.getElementById('search');let activeCategory='all';
const filterBar=document.getElementById('commandFilters');
function render(q=''){const query=q.toLowerCase().replace('/','').trim();const matches=commands.filter(c=>c.includes(query)&&(activeCategory==='all'||category(c)===activeCategory));grid.innerHTML='';matches.forEach(c=>{const b=document.createElement('button');b.className='cmd';b.dataset.category=category(c);b.innerHTML=`<span>/${c}</span><small>${category(c).toUpperCase()}</small>`;b.onclick=()=>copyCmd('/'+c);grid.appendChild(b)});if(!matches.length)grid.innerHTML='<p class="muted">No command found. Xenoxy is powerful, not psychic 😭</p>';const count=document.getElementById('commandCount');if(count)count.textContent=`${matches.length} shown`}
function copyCmd(cmd){navigator.clipboard.writeText(cmd);const t=document.getElementById('toast');t.textContent=`Copied ${cmd}`;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1200)}
search?.addEventListener('input',e=>render(e.target.value));filterBar?.addEventListener('click',e=>{const b=e.target.closest('button[data-filter]');if(!b)return;activeCategory=b.dataset.filter;filterBar.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));render(search?.value||'')});render();
const topNav=document.querySelector('nav');function updateTopNav(){if(!topNav)return;const y=window.scrollY||document.documentElement.scrollTop;topNav.classList.toggle('nav-fading',y>70&&y<=155);topNav.classList.toggle('nav-hidden',y>155)}window.addEventListener('scroll',updateTopNav,{passive:true});updateTopNav();
const xenoxyMark=`<svg viewBox="0 0 64 64" aria-hidden="true" class="xenoxy-mark"><defs><linearGradient id="xenoCore" x1="10" y1="8" x2="54" y2="56"><stop stop-color="#fff"/><stop offset=".28" stop-color="#d8b4fe"/><stop offset=".62" stop-color="#a855f7"/><stop offset="1" stop-color="#ff4fd8"/></linearGradient><linearGradient id="xenoOrbit" x1="8" y1="54" x2="56" y2="10"><stop stop-color="#7c3aed"/><stop offset=".52" stop-color="#c084fc"/><stop offset="1" stop-color="#ff4fd8"/></linearGradient></defs><ellipse cx="32" cy="32" rx="28" ry="11" transform="rotate(-24 32 32)" fill="none" stroke="url(#xenoOrbit)" stroke-width="1.8"/><path d="M15.5 12.8 32 28.1l16.5-15.3 5 5.3L37.6 32.6 53.5 47.4l-5 5.3L32 37.3 15.5 52.7l-5-5.3 15.9-14.8L10.5 18.1l5-5.3Z" fill="url(#xenoCore)"/><circle cx="50.7" cy="18.8" r="2.25" fill="#fff"/></svg>`;
document.querySelectorAll('.logo').forEach(el=>{el.innerHTML=xenoxyMark;el.classList.add('xenoxy-logo-upgraded')});document.querySelectorAll('.mini-x').forEach(el=>{el.innerHTML=xenoxyMark;el.classList.add('xenoxy-mini-upgraded')});
