const commands=['ping','help','userinfo','avatar','joined','serverinfo','servericon','roleinfo','channelinfo','botinfo','uptime','roles','permissions','8ball','coinflip','roll','dice','choose','randomnumber','rate','ship','rps','joke','fact','truth','dare','wouldyourather','compliment','roast','vibecheck','iq','howgay','slots','say','poll','announce','timestamp','calc','remindme','password','color','countdown','embed','length','choose-number','clear','kick','ban','unban','timeout','untimeout','slowmode','nickname','lock','unlock','purge-user','role-add','role-remove','move','channel-create','channel-delete','role-create','role-delete','server-stats','bot-stats','invite','rules','setup','welcome-channel','welcome-toggle','goodbye-channel','goodbye-toggle','log-channel','autorole','autorole-off','suggestion-setup','suggestion','report','server-backup','reaction-role','button-role','setup-reset','birthday','confess','server-health','role-menu','welcome-preview','activity','sticky','embed-builder','verification-setup','suggestion-manage','birthday-list','birthday-remove','sticky-off','confess-setup','member-stats','verification-off','server-age','about'];
const moderation=new Set(['clear','kick','ban','unban','timeout','untimeout','slowmode','nickname','lock','unlock','purge-user','role-add','role-remove','move','report']);
const community=new Set(['suggestion-setup','suggestion','reaction-role','button-role','birthday','confess','role-menu','activity','sticky','suggestion-manage','birthday-list','birthday-remove','sticky-off','confess-setup']);
const server=new Set(['channel-create','channel-delete','role-create','role-delete','server-stats','invite','rules','setup','welcome-channel','welcome-toggle','goodbye-channel','goodbye-toggle','log-channel','autorole','autorole-off','server-backup','setup-reset','welcome-preview','verification-setup','verification-off','server-health','server-age']);
const fun=new Set(['8ball','coinflip','roll','dice','choose','randomnumber','rate','ship','rps','joke','fact','truth','dare','wouldyourather','compliment','roast','vibecheck','iq','howgay','slots']);
const category=c=>moderation.has(c)?'moderation':community.has(c)?'community':server.has(c)?'server':fun.has(c)?'fun':'utility';
const grid=document.getElementById('commandGrid'),search=document.getElementById('search'),filterBar=document.getElementById('commandFilters');let activeCategory='all';
function render(q=''){const query=q.toLowerCase().replace('/','').trim();const matches=commands.filter(c=>c.includes(query)&&(activeCategory==='all'||category(c)===activeCategory));grid.innerHTML='';matches.forEach(c=>{const b=document.createElement('button');b.className='cmd';b.dataset.category=category(c);b.innerHTML=`<span>/${c}</span><small>${category(c).toUpperCase()}</small>`;b.onclick=()=>copyCmd('/'+c);grid.appendChild(b)});if(!matches.length)grid.innerHTML='<p class="muted">No command found. Xenoxy is powerful, not psychic 😭</p>';const count=document.getElementById('commandCount');if(count)count.textContent=`${matches.length} shown`}
function copyCmd(cmd){navigator.clipboard.writeText(cmd);const t=document.getElementById('toast');t.textContent=`Copied ${cmd}`;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1200)}
search?.addEventListener('input',e=>render(e.target.value));filterBar?.addEventListener('click',e=>{const b=e.target.closest('button[data-filter]');if(!b)return;activeCategory=b.dataset.filter;filterBar.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));render(search?.value||'')});render();
const reduceMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const topNav=document.querySelector('nav');function updateTopNav(){if(!topNav)return;const y=window.scrollY||document.documentElement.scrollTop;topNav.classList.toggle('nav-fading',y>70&&y<=155);topNav.classList.toggle('nav-hidden',y>155)}window.addEventListener('scroll',updateTopNav,{passive:true});updateTopNav();
const xenoxyMark=`<svg viewBox="0 0 64 64" aria-hidden="true" class="xenoxy-mark"><defs><linearGradient id="xenoCore" x1="10" y1="8" x2="54" y2="56"><stop stop-color="#fff"/><stop offset=".28" stop-color="#d8b4fe"/><stop offset=".62" stop-color="#a855f7"/><stop offset="1" stop-color="#ff4fd8"/></linearGradient><linearGradient id="xenoOrbit" x1="8" y1="54" x2="56" y2="10"><stop stop-color="#7c3aed"/><stop offset=".52" stop-color="#c084fc"/><stop offset="1" stop-color="#ff4fd8"/></linearGradient></defs><ellipse cx="32" cy="32" rx="28" ry="11" transform="rotate(-24 32 32)" fill="none" stroke="url(#xenoOrbit)" stroke-width="1.8"/><path d="M15.5 12.8 32 28.1l16.5-15.3 5 5.3L37.6 32.6 53.5 47.4l-5 5.3L32 37.3 15.5 52.7l-5-5.3 15.9-14.8L10.5 18.1l5-5.3Z" fill="url(#xenoCore)"/><circle cx="50.7" cy="18.8" r="2.25" fill="#fff"/></svg>`;document.querySelectorAll('.logo').forEach(el=>{el.innerHTML=xenoxyMark;el.classList.add('xenoxy-logo-upgraded')});document.querySelectorAll('.mini-x').forEach(el=>{el.innerHTML=xenoxyMark;el.classList.add('xenoxy-mini-upgraded')});
const revealTargets=[...document.querySelectorAll('.sectionhead,.metric-strip article,.cards article,.guide-grid article,.contact-card,.searchwrap,.command-toolbar,.command-grid,.hero-console')];revealTargets.forEach(el=>el.classList.add('x-reveal'));if(reduceMotion||!('IntersectionObserver'in window))revealTargets.forEach(el=>el.classList.add('is-visible'));else{const io=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');io.unobserve(entry.target)}}),{threshold:.1,rootMargin:'0px 0px -6% 0px'});revealTargets.forEach(el=>io.observe(el))}
const consoleEl=document.querySelector('.hero-console');if(consoleEl&&!reduceMotion&&matchMedia('(pointer:fine)').matches){consoleEl.addEventListener('pointermove',e=>{const r=consoleEl.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;consoleEl.style.setProperty('--tilt-x',`${x*5.5}deg`);consoleEl.style.setProperty('--tilt-y',`${y*-4.5}deg`)});consoleEl.addEventListener('pointerleave',()=>{consoleEl.style.setProperty('--tilt-x','0deg');consoleEl.style.setProperty('--tilt-y','0deg')})}
const telemetry=[...document.querySelectorAll('.metric-strip b')];telemetry.forEach(el=>{const m=el.textContent.trim().match(/^(\d+)(.*)$/);if(!m||reduceMotion)return;el.dataset.target=m[1];el.dataset.suffix=m[2];el.textContent=`0${m[2]}`});if(!reduceMotion&&'IntersectionObserver'in window){const mo=new IntersectionObserver(entries=>entries.forEach(entry=>{if(!entry.isIntersecting)return;const el=entry.target,target=Number(el.dataset.target),suffix=el.dataset.suffix||'',start=performance.now();const tick=now=>{const p=Math.min(1,(now-start)/750),eased=1-Math.pow(1-p,3);el.textContent=`${Math.round(target*eased)}${suffix}`;if(p<1)requestAnimationFrame(tick)};requestAnimationFrame(tick);mo.unobserve(el)}),{threshold:.4});telemetry.filter(el=>el.dataset.target).forEach(el=>mo.observe(el))}
const progress=document.createElement('div');progress.className='x-scroll-progress';document.body.appendChild(progress);const updateProgress=()=>{const h=document.documentElement.scrollHeight-innerHeight;progress.style.transform=`scaleX(${h>0?scrollY/h:0})`};window.addEventListener('scroll',updateProgress,{passive:true});window.addEventListener('resize',updateProgress,{passive:true});updateProgress();
if(!reduceMotion&&matchMedia('(pointer:fine)').matches){document.querySelectorAll('.cards article,.contact-card,.guide-grid article').forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect();el.style.setProperty('--px',`${e.clientX-r.left}px`);el.style.setProperty('--py',`${e.clientY-r.top}px`)})})}
document.addEventListener('keydown',e=>{if(e.key==='/'&&document.activeElement?.tagName!=='INPUT'){e.preventDefault();search?.focus();search?.select()}if(e.key==='Escape'&&search&&document.activeElement===search){search.value='';activeCategory='all';filterBar?.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.filter==='all'));render();search.blur()}});
